### PR TITLE
Allow pagination on donors/show page

### PR DESCRIPTION
**Pull request by limxinyuuu**
This change adds pagination to the donors/show page.

---

**Before submitting, check that:**

 - [ ] You have added (passing) tests for your code.
 - [x] You have written good* commit messages.
 - [x] You have squashed relevant commits together.
 - [x] You have ensured that RuboCop is passing.
 - [x] Your PR relates to one subject, with a clear title and
       description using complete, grammatically correct sentences.

*If you do not know what makes a good commit message, or why it
is important, please refer to these resources: [1][1], [2][2], [3][3].

[1]: https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
[2]: http://chris.beams.io/posts/git-commit/
[3]: https://github.com/blog/1943-how-to-write-the-perfect-pull-request

### CODE REVIEW

**Comment by Drenmi** [comment]
Travis not happy. 😞

**Comment by Drenmi** [comment]
I fixed the failing test case. There are some merge conflicts in `donors/show.html.slim` that is probably best resolved between you: @alahab2, @limxinyuuu 😀

**Comment by alahab2** [comment]
Fixed the conflicts and updated `will_paginate` syntax.

**Comment by Drenmi** [comment]
Thanks, @alahab2! 🍚

**Pull request merged**
